services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  nest-app:
    build: .
    container_name: nest_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend
    command: npm run start:dev  # o "node dist/main" si estás en producción

volumes:
  pg_data:
  redis_data:

networks:
  backend:
