-- Table structure for table `languages`

CREATE TABLE IF NOT EXISTS languages (
  id SERIAL PRIMARY KEY,
  language_code VARCHAR(10) NOT NULL,
  language_name VARCHAR(100) NOT NULL
);


INSERT INTO languages (id, language_code, language_name) VALUES
(1, 'af', 'Afrikaans'),
(2, 'sq', 'Albanian - shqip'),
(3, 'am', 'Amharic - አማርኛ'),
(4, 'ar', 'Arabic - العربية'),
(5, 'an', 'Aragonese - aragonés'),
(6, 'hy', 'Armenian - հայերեն'),
(7, 'ast', 'Asturian - asturianu'),
(8, 'az', 'Azerbaijani - azərbaycan dili'),
(9, 'eu', 'Basque - euskara'),
(10, 'be', 'Belarusian - беларуская'),
(11, 'bn', 'Bengali - বাংলা'),
(12, 'bs', 'Bosnian - bosanski'),
(13, 'br', 'Breton - brezhoneg'),
(14, 'bg', 'Bulgarian - български'),
(15, 'ca', 'Catalan - català'),
(16, 'ckb', 'Central Kurdish - کوردی (دەستنوسی عەرەبی)'),
(17, 'zh', 'Chinese - 中文'),
(18, 'zh-HK', 'Chinese (Hong Kong) - 中文（香港）'),
(19, 'zh-CN', 'Chinese (Simplified) - 中文（简体）'),
(20, 'zh-TW', 'Chinese (Traditional) - 中文（繁體）'),
(21, 'co', 'Corsican'),
(22, 'hr', 'Croatian - hrvatski'),
(23, 'cs', 'Czech - čeština'),
(24, 'da', 'Danish - dansk'),
(25, 'nl', 'Dutch - Nederlands'),
(26, 'en', 'English'),
(27, 'en-AU', 'English (Australia)'),
(28, 'en-CA', 'English (Canada)'),
(29, 'en-IN', 'English (India)'),
(30, 'en-NZ', 'English (New Zealand)'),
(31, 'en-ZA', 'English (South Africa)'),
(32, 'en-GB', 'English (United Kingdom)'),
(33, 'en-US', 'English (United States)'),
(34, 'eo', 'Esperanto - esperanto'),
(35, 'et', 'Estonian - eesti'),
(36, 'fo', 'Faroese - føroyskt'),
(37, 'fil', 'Filipino'),
(38, 'fi', 'Finnish - suomi'),
(39, 'fr', 'French - français'),
(40, 'fr-CA', 'French (Canada) - français (Canada)'),
(41, 'fr-FR', 'French (France) - français (France)'),
(42, 'fr-CH', 'French (Switzerland) - français (Suisse)'),
(43, 'gl', 'Galician - galego'),
(44, 'ka', 'Georgian - ქართული'),
(45, 'de', 'German - Deutsch'),
(46, 'de-AT', 'German (Austria) - Deutsch (Österreich)'),
(47, 'de-DE', 'German (Germany) - Deutsch (Deutschland)'),
(48, 'de-LI', 'German (Liechtenstein) - Deutsch (Liechtenstein)'),
(49, 'de-CH', 'German (Switzerland) - Deutsch (Schweiz)'),
(50, 'el', 'Greek - Ελληνικά'),
(51, 'gn', 'Guarani'),
(52, 'gu', 'Gujarati - ગુજરાતી'),
(53, 'ha', 'Hausa'),
(54, 'haw', 'Hawaiian - ʻŌlelo Hawaiʻi'),
(55, 'he', 'Hebrew - עברית'),
(56, 'hi', 'Hindi - हिन्दी'),
(57, 'hu', 'Hungarian - magyar'),
(58, 'is', 'Icelandic - íslenska'),
(59, 'id', 'Indonesian - Indonesia'),
(60, 'ia', 'Interlingua'),
(61, 'ga', 'Irish - Gaeilge'),
(62, 'it', 'Italian - italiano'),
(63, 'it-IT', 'Italian (Italy) - italiano (Italia)'),
(64, 'it-CH', 'Italian (Switzerland) - italiano (Svizzera)'),
(65, 'ja', 'Japanese - 日本語'),
(66, 'kn', 'Kannada - ಕನ್ನಡ'),
(67, 'kk', 'Kazakh - қазақ тілі'),
(68, 'km', 'Khmer - ខ្មែរ'),
(69, 'ko', 'Korean - 한국어'),
(70, 'ku', 'Kurdish - Kurdî'),
(71, 'ky', 'Kyrgyz - кыргызча'),
(72, 'lo', 'Lao - ລາວ'),
(73, 'la', 'Latin'),
(74, 'lv', 'Latvian - latviešu'),
(75, 'ln', 'Lingala - lingála'),
(76, 'lt', 'Lithuanian - lietuvių'),
(77, 'mk', 'Macedonian - македонски'),
(78, 'ms', 'Malay - Bahasa Melayu'),
(79, 'ml', 'Malayalam - മലയാളം'),
(80, 'mt', 'Maltese - Malti'),
(81, 'mr', 'Marathi - मराठी'),
(82, 'mn', 'Mongolian - монгол'),
(83, 'ne', 'Nepali - नेपाली'),
(84, 'no', 'Norwegian - norsk'),
(85, 'nb', 'Norwegian Bokmål - norsk bokmål'),
(86, 'nn', 'Norwegian Nynorsk - nynorsk'),
(87, 'oc', 'Occitan'),
(88, 'or', 'Oriya - ଓଡ଼ିଆ'),
(89, 'om', 'Oromo - Oromoo'),
(90, 'ps', 'Pashto - پښتو'),
(91, 'fa', 'Persian - فارسی'),
(92, 'pl', 'Polish - polski'),
(93, 'pt', 'Portuguese - português'),
(94, 'pt-BR', 'Portuguese (Brazil) - português (Brasil)'),
(95, 'pt-PT', 'Portuguese (Portugal) - português (Portugal)'),
(96, 'pa', 'Punjabi - ਪੰਜਾਬੀ'),
(97, 'qu', 'Quechua'),
(98, 'ro', 'Romanian - română'),
(99, 'mo', 'Romanian (Moldova) - română (Moldova)'),
(100, 'rm', 'Romansh - rumantsch'),
(101, 'ru', 'Russian - русский'),
(102, 'gd', 'Scottish Gaelic'),
(103, 'sr', 'Serbian - српски'),
(104, 'sh', 'Serbo-Croatian - Srpskohrvatski'),
(105, 'sn', 'Shona - chiShona'),
(106, 'sd', 'Sindhi'),
(107, 'si', 'Sinhala - සිංහල'),
(108, 'sk', 'Slovak - slovenčina'),
(109, 'sl', 'Slovenian - slovenščina'),
(110, 'so', 'Somali - Soomaali'),
(111, 'st', 'Southern Sotho'),
(112, 'es', 'Spanish - español'),
(113, 'es-AR', 'Spanish (Argentina) - español (Argentina)'),
(114, 'es-419', 'Spanish (Latin America) - español (Latinoamérica)'),
(115, 'es-MX', 'Spanish (Mexico) - español (México)'),
(116, 'es-ES', 'Spanish (Spain) - español (España)'),
(117, 'es-US', 'Spanish (United States) - español (Estados Unidos)'),
(118, 'su', 'Sundanese'),
(119, 'sw', 'Swahili - Kiswahili'),
(120, 'sv', 'Swedish - svenska'),
(121, 'tg', 'Tajik - тоҷикӣ'),
(122, 'ta', 'Tamil - தமிழ்'),
(123, 'tt', 'Tatar'),
(124, 'te', 'Telugu - తెలుగు'),
(125, 'th', 'Thai - ไทย'),
(126, 'ti', 'Tigrinya - ትግርኛ'),
(127, 'to', 'Tongan - lea fakatonga'),
(128, 'tr', 'Turkish - Türkçe'),
(129, 'tk', 'Turkmen'),
(130, 'tw', 'Twi'),
(131, 'uk', 'Ukrainian - українська'),
(132, 'ur', 'Urdu - اردو'),
(133, 'ug', 'Uyghur'),
(134, 'uz', 'Uzbek - o‘zbek'),
(135, 'vi', 'Vietnamese - Tiếng Việt'),
(136, 'wa', 'Walloon - wa'),
(137, 'cy', 'Welsh - Cymraeg'),
(138, 'fy', 'Western Frisian'),
(139, 'xh', 'Xhosa'),
(140, 'yi', 'Yiddish'),
(141, 'yo', 'Yoruba - Èdè Yorùbá'),
(142, 'zu', 'Zulu - isiZulu');

-- All countries

CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    code char(2) NOT NULL,
    name varchar(100) NOT NULL
); 

INSERT INTO countries (id, code, name) VALUES
(1, 'AF', 'Afghanistan'),
(2, 'AX', 'Åland Islands'),
(3, 'AL', 'Albania'),
(4, 'DZ', 'Algeria'),
(5, 'AS', 'American Samoa'),
(6, 'AD', 'Andorra'),
(7, 'AO', 'Angola'),
(8, 'AI', 'Anguilla'),
(9, 'AQ', 'Antarctica'),
(10, 'AG', 'Antigua & Barbuda'),
(11, 'AR', 'Argentina'),
(12, 'AM', 'Armenia'),
(13, 'AW', 'Aruba'),
(14, 'AU', 'Australia'),
(15, 'AT', 'Austria'),
(16, 'AZ', 'Azerbaijan'),
(17, 'BS', 'Bahamas'),
(18, 'BH', 'Bahrain'),
(19, 'BD', 'Bangladesh'),
(20, 'BB', 'Barbados'),
(21, 'BY', 'Belarus'),
(22, 'BE', 'Belgium'),
(23, 'BZ', 'Belize'),
(24, 'BJ', 'Benin'),
(25, 'BM', 'Bermuda'),
(26, 'BT', 'Bhutan'),
(27, 'BO', 'Bolivia'),
(28, 'BA', 'Bosnia & Herzegovina'),
(29, 'BW', 'Botswana'),
(30, 'BV', 'Bouvet Island'),
(31, 'BR', 'Brazil'),
(32, 'IO', 'British Indian Ocean Territory'),
(33, 'BN', 'Brunei'),
(34, 'BG', 'Bulgaria'),
(35, 'BF', 'Burkina Faso'),
(36, 'BI', 'Burundi'),
(37, 'CV', 'Cape Verde'),
(38, 'KH', 'Cambodia'),
(39, 'CM', 'Cameroon'),
(40, 'CA', 'Canada'),
(41, 'BQ', 'Caribbean Netherlands'),
(42, 'KY', 'Cayman Islands'),
(43, 'CF', 'Central African Republic'),
(44, 'TD', 'Chad'),
(45, 'CL', 'Chile'),
(46, 'CN', 'China'),
(47, 'CX', 'Christmas Island'),
(48, 'CC', 'Cocos (Keeling) Islands'),
(49, 'CO', 'Colombia'),
(50, 'KM', 'Comoros'),
(51, 'CG', 'Congo - Brazzaville'),
(52, 'CD', 'Congo - Kinshasa'),
(53, 'CK', 'Cook Islands'),
(54, 'CR', 'Costa Rica'),
(55, 'HR', 'Croatia'),
(56, 'CU', 'Cuba'),
(57, 'CW', 'Curaçao'),
(58, 'CY', 'Cyprus'),
(59, 'CZ', 'Czechia'),
(60, 'CI', 'Côte d’Ivoire'),
(61, 'DK', 'Denmark'),
(62, 'DJ', 'Djibouti'),
(63, 'DM', 'Dominica'),
(64, 'DO', 'Dominican Republic'),
(65, 'EC', 'Ecuador'),
(66, 'EG', 'Egypt'),
(67, 'SV', 'El Salvador'),
(68, 'GQ', 'Equatorial Guinea'),
(69, 'ER', 'Eritrea'),
(70, 'EE', 'Estonia'),
(71, 'SZ', 'Eswatini'),
(72, 'ET', 'Ethiopia'),
(73, 'FK', 'Falkland Islands (Islas Malvinas)'),
(74, 'FO', 'Faroe Islands'),
(75, 'FJ', 'Fiji'),
(76, 'FI', 'Finland'),
(77, 'FR', 'France'),
(78, 'GF', 'French Guiana'),
(79, 'PF', 'French Polynesia'),
(80, 'TF', 'French Southern Territories'),
(81, 'GA', 'Gabon'),
(82, 'GM', 'Gambia'),
(83, 'GE', 'Georgia'),
(84, 'DE', 'Germany'),
(85, 'GH', 'Ghana'),
(86, 'GI', 'Gibraltar'),
(87, 'GR', 'Greece'),
(88, 'GL', 'Greenland'),
(89, 'GD', 'Grenada'),
(90, 'GP', 'Guadeloupe'),
(91, 'GU', 'Guam'),
(92, 'GT', 'Guatemala'),
(93, 'GG', 'Guernsey'),
(94, 'GN', 'Guinea'),
(95, 'GW', 'Guinea-Bissau'),
(96, 'GY', 'Guyana'),
(97, 'HT', 'Haiti'),
(98, 'HM', 'Heard & McDonald Islands'),
(99, 'HN', 'Honduras'),
(100, 'HK', 'Hong Kong'),
(101, 'HU', 'Hungary'),
(102, 'IS', 'Iceland'),
(103, 'IN', 'India'),
(104, 'ID', 'Indonesia'),
(105, 'IR', 'Iran'),
(106, 'IQ', 'Iraq'),
(107, 'IE', 'Ireland'),
(108, 'IM', 'Isle of Man'),
(109, 'IL', 'Israel'),
(110, 'IT', 'Italy'),
(111, 'JM', 'Jamaica'),
(112, 'JP', 'Japan'),
(113, 'JE', 'Jersey'),
(114, 'JO', 'Jordan'),
(115, 'KZ', 'Kazakhstan'),
(116, 'KE', 'Kenya'),
(117, 'KI', 'Kiribati'),
(118, 'KP', 'North Korea'),
(119, 'KR', 'South Korea'),
(120, 'XK', 'Kosovo'),
(121, 'KW', 'Kuwait'),
(122, 'KG', 'Kyrgyzstan'),
(123, 'LA', 'Laos'),
(124, 'LV', 'Latvia'),
(125, 'LB', 'Lebanon'),
(126, 'LS', 'Lesotho'),
(127, 'LR', 'Liberia'),
(128, 'LY', 'Libya'),
(129, 'LI', 'Liechtenstein'),
(130, 'LT', 'Lithuania'),
(131, 'LU', 'Luxembourg'),
(132, 'MO', 'Macao'),
(133, 'MK', 'North Macedonia'),
(134, 'MG', 'Madagascar'),
(135, 'MW', 'Malawi'),
(136, 'MY', 'Malaysia'),
(137, 'MV', 'Maldives'),
(138, 'ML', 'Mali'),
(139, 'MT', 'Malta'),
(140, 'MH', 'Marshall Islands'),
(141, 'MQ', 'Martinique'),
(142, 'MR', 'Mauritania'),
(143, 'MU', 'Mauritius'),
(144, 'YT', 'Mayotte'),
(145, 'MX', 'Mexico'),
(146, 'FM', 'Micronesia'),
(147, 'MD', 'Moldova'),
(148, 'MC', 'Monaco'),
(149, 'MN', 'Mongolia'),
(150, 'ME', 'Montenegro'),
(151, 'MS', 'Montserrat'),
(152, 'MA', 'Morocco'),
(153, 'MZ', 'Mozambique'),
(154, 'MM', 'Myanmar (Burma)'),
(155, 'NA', 'Namibia'),
(156, 'NR', 'Nauru'),
(157, 'NP', 'Nepal'),
(158, 'NL', 'Netherlands'),
(159, 'AN', 'Curaçao'),
(160, 'NC', 'New Caledonia'),
(161, 'NZ', 'New Zealand'),
(162, 'NI', 'Nicaragua'),
(163, 'NE', 'Niger'),
(164, 'NG', 'Nigeria'),
(165, 'NU', 'Niue'),
(166, 'NF', 'Norfolk Island'),
(167, 'MP', 'Northern Mariana Islands'),
(168, 'NO', 'Norway'),
(169, 'OM', 'Oman'),
(170, 'PK', 'Pakistan'),
(171, 'PW', 'Palau'),
(172, 'PS', 'Palestine'),
(173, 'PA', 'Panama'),
(174, 'PG', 'Papua New Guinea'),
(175, 'PY', 'Paraguay'),
(176, 'PE', 'Peru'),
(177, 'PH', 'Philippines'),
(178, 'PN', 'Pitcairn Islands'),
(179, 'PL', 'Poland'),
(180, 'PT', 'Portugal'),
(181, 'PR', 'Puerto Rico'),
(182, 'QA', 'Qatar'),
(183, 'RE', 'Réunion'),
(184, 'RO', 'Romania'),
(185, 'RU', 'Russia'),
(186, 'RW', 'Rwanda'),
(187, 'BL', 'St. Barthélemy'),
(188, 'SH', 'St. Helena'),
(189, 'KN', 'St. Kitts & Nevis'),
(190, 'LC', 'St. Lucia'),
(191, 'MF', 'St. Martin'),
(192, 'PM', 'St. Pierre & Miquelon'),
(193, 'VC', 'St. Vincent & Grenadines'),
(194, 'WS', 'Samoa'),
(195, 'SM', 'San Marino'),
(196, 'ST', 'São Tomé & Príncipe'),
(197, 'SA', 'Saudi Arabia'),
(198, 'SN', 'Senegal'),
(199, 'RS', 'Serbia'),
(200, 'CS', 'Serbia'),
(201, 'SC', 'Seychelles'),
(202, 'SL', 'Sierra Leone'),
(203, 'SG', 'Singapore'),
(204, 'SX', 'Sint Maarten'),
(205, 'SK', 'Slovakia'),
(206, 'SI', 'Slovenia'),
(207, 'SB', 'Solomon Islands'),
(208, 'SO', 'Somalia'),
(209, 'ZA', 'South Africa'),
(210, 'GS', 'South Georgia & South Sandwich Islands'),
(211, 'SS', 'South Sudan'),
(212, 'ES', 'Spain'),
(213, 'LK', 'Sri Lanka'),
(214, 'SD', 'Sudan'),
(215, 'SR', 'Suriname'),
(216, 'SJ', 'Svalbard & Jan Mayen'),
(217, 'SE', 'Sweden'),
(218, 'CH', 'Switzerland'),
(219, 'SY', 'Syria'),
(220, 'TW', 'Taiwan'),
(221, 'TJ', 'Tajikistan'),
(222, 'TZ', 'Tanzania'),
(223, 'TH', 'Thailand'),
(224, 'TL', 'Timor-Leste'),
(225, 'TG', 'Togo'),
(226, 'TK', 'Tokelau'),
(227, 'TO', 'Tonga'),
(228, 'TT', 'Trinidad & Tobago'),
(229, 'TN', 'Tunisia'),
(230, 'TR', 'Türkiye'),
(231, 'TM', 'Turkmenistan'),
(232, 'TC', 'Turks & Caicos Islands'),
(233, 'TV', 'Tuvalu'),
(234, 'UM', 'U.S. Outlying Islands'),
(235, 'UG', 'Uganda'),
(236, 'UA', 'Ukraine'),
(237, 'AE', 'United Arab Emirates'),
(238, 'GB', 'United Kingdom'),
(239, 'US', 'United States'),
(240, 'UY', 'Uruguay'),
(241, 'UZ', 'Uzbekistan'),
(242, 'VU', 'Vanuatu'),
(243, 'VA', 'Vatican City'),
(244, 'VE', 'Venezuela'),
(245, 'VN', 'Vietnam'),
(246, 'VG', 'British Virgin Islands'),
(247, 'VI', 'U.S. Virgin Islands'),
(248, 'WF', 'Wallis & Futuna'),
(249, 'EH', 'Western Sahara'),
(250, 'YE', 'Yemen'),
(251, 'ZM', 'Zambia'),
(252, 'ZW', 'Zimbabwe');

CREATE TABLE experience (
    id SERIAL PRIMARY KEY,
    description VARCHAR(50) NOT NULL
);

INSERT INTO experience (description) VALUES
('No experience'),
('Less than 2 years'),
('3 – 5 years'),
('6 – 10 years'),
('More than 10 years');


CREATE TABLE testing_interest (
    id SERIAL PRIMARY KEY,
    description VARCHAR(100) NOT NULL
);

INSERT INTO testing_interest (description) VALUES
('Manual and exploratory testing'),
('Automated testing'),
('AI testing'),
('Cybersecurity testing'),
('Performance testing'),
('API / microservices testing'),
('Mobile app testing'),
('Behavior Driven Development'),
('Test Driven Development'),
('Other types of testing (please specify)');


CREATE TABLE tester (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(100) not null,
    surname VARCHAR(100) not null,
    email VARCHAR(100) not null, 
    birth_date DATE NOT NULL CHECK (birth_date <= CURRENT_DATE - INTERVAL '18 years'),
    
    languages INT REFERENCES languages(id),  -- solo un idioma
    city VARCHAR(100),
    postal_code VARCHAR(20),
    
    country INT REFERENCES countries(id),
    experience_level INT REFERENCES experience(id),

    interests INT[],  -- sigue siendo un array de IDs (de testing_interest)
    userId VARCHAR(50),
    password TEXT;
);

CREATE TABLE customers ( 
  NIF VARCHAR(20) NOT NULL,
  companyName VARCHAR(100) NOT NULL,
  taxDomicile VARCHAR(150) NOT NULL,
  id VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  userid VARCHAR(50),
  password VARCHAR(255),
  CONSTRAINT "PK_72355502f9f4a98aa6eacfad6c2" PRIMARY KEY ("NIF"),
  CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email")
);